Analysis/in datatypes
uxmal/reko pull request #1165
Opened 2022-03-19 01:32 UTC by uxmal

This PR uses a variant of the `ExpressionTypeDescender` to extract type information from local procedures. This helps us eliminate more `fp-XX` expressions and replace them with `&tLocXX`.

2022-03-19 13:13 UTC, ptomin requested changes
I have added some notes.

2022-03-19 13:55 UTC, ptomin commented
One more note: it still not work for https://github.com/uxmal/reko/blame/master/subjects/PE/x86/LocalStackVariables sample

2022-03-19 15:25 UTC, uxmal commented on src/Decompiler/Typing/ExpressionTypeDescender.cs
> +                //throw new TypeInferenceException($"Not handling {dtDiff} and {dtSub} yet.");
Done. Note how the new `DataType.Domain` property pays off in simplifying the code.

2022-03-19 15:25 UTC, uxmal commented on src/Decompiler/Typing/ExpressionTypeDescender.cs
> +                //throw new TypeInferenceException(string.Format("Not handling {0} and {1} yet", dtDiff, dtMin));
Done.

2022-03-19 15:28 UTC, uxmal commented on src/Core/Expressions/PhiFunction.cs
> +        }
Actually, it's used in places where the `PhiArgument` is deconstructed. For instance in the code starting on line 52 in `LocalTypeDescender.cs`:
```C#
                    var tv = TypeVar(phi.Dst);
                    foreach (var (_, v) in phi.Src.Arguments)
                    {
                        store.MergeClasses(tv, TypeVar(v));
                    }
```
The `(_, v)` is deconstructing the `PhiArgument` by calling the `Deconstruct` method.

2022-03-19 15:54 UTC, ptomin commented on src/Core/Expressions/PhiFunction.cs
> +        }
Oh, `Deconstruct` is magic method. I did not know that.

2022-03-19 18:56 UTC, uxmal commented
@ptomin : I looked at `LocalStackVariables`. The machine code is 
```

00401022 lea eax,[ebp-18h]
00401025 push eax
00401026 lea ecx,[ebp-28h]
00401029 push ecx
0040102A call GetMin
```
which gets rewritten, SSA converted and value propagated to:
```
	// res = GetMin(&s1, &s2)
	eax_20 = fp - 28<i32>
	esp_21 = fp - 0x30<32>
	Mem22[fp - 0x30<32>:word32] = fp - 28<i32>
	ecx_23 = fp - 44<i32>
	esp_24 = fp - 0x34<32>
	Mem25[fp - 0x34<32>:word32] = fp - 44<i32>
	call GetMin (retsize: 4;)
		uses: Stack +0004:Mem25[fp - 0x34<32>:word32],Stack +0008:Mem25[fp - 0x30<32>:word32]
		defs: C:C_31,eax:eax_26,ecx:ecx_27,edx:edx_28,FPUF:FPUF_29,O:O_33,S:S_30,Z:Z_32
```
Value propagation has not occurred on the arguments to `GetMin` because they are not registers/identifiers; they are in the form of `Memxx[fp - XX]`. The logic in `EscapedFrameIntervalsFinder.IsFrameAccess` expect arguments to be of the form `fp-XX`. 

A future commit will have to address this by walking the stack backwards from the `call` to detect arguments pushed on the stack and resolve them that way.

2022-03-19 21:04 UTC, uxmal commented on subjects/Elf/ARM/angr-685/RTOSDemo.reko/RTOSDemo_text.c
>  		xQueueGenericSendFromISR(fp - 0x15, r0_n, fp - 20, 0x00, lr, cpsr);
Fixed on my machine.

2022-03-19 21:05 UTC, uxmal commented on src/Core/Expressions/PhiFunction.cs
> +        }
C# is a growing language. Soon it will be as huge as C++ :)

2022-03-20 06:40 UTC, ptomin commented
`EscapedFrameIntervalsFinder` designed to make possible to do such transformations. `EscapedFrameIntervalsFinder.Context` (implementation of ` EvaluationContext`) should do its job properly even for Memory Accesses propagation. So walking the stack backwards is not required.
Are you sure that data types of `GetMin` call parameters discovered correctly by `UserRegisterFinder`/` LocalTypeDescender`?

2022-03-21 15:34 UTC, uxmal commented
@ptomin : this is starting to look pretty good.

2022-03-21 16:42 UTC, ptomin commented on subjects/PE/x86/LocalStackVariables/LocalStackVariables.reko/LocalStackVariables_text.c
> +	tLoc1C.r0008 = 11.0;
Nice output!

2022-03-21 17:10 UTC, ptomin approved these changes
Looks good, now.

2022-03-21 18:17 UTC, closed without merging